### ISSUE TITLE
Can't get DefaultNavigation to navigate

### ISSUE THREAD

**Issue by indyjason79** [AvantiPoint/mauimicromvvm#1]
Absolutely love this package! I can't seem to get the DefaultNavigation to work at all though. I even pulled your sample project and instead of making the button count I tried to navigate to the MessageDemoPage and nothing happens. 

I tried 3 different ways: 

Using the Navigation property on the base view model:
`this.PressedCommand = new Command(async () => await base.Navigation.GoToAsync(nameof(MessageDemoPage)));`

Injecting Shell into the concrete viewmodel and using that:
`this.PressedCommand = new Command(async () => await shell.GoToAsync(nameof(MessageDemoPage)));`

Using the ViewModelContext.Navigation:
`this.PressedCommand = new Command(async () => await context.Navigation.GoToAsync(nameof(MessageDemoPage)));`

I should also note, using `Shell.Current.GoToAsync` does work. Using `Shell.GoToAsync` when Shell is injected does not seem to work.

I'm sure it's something stupid I'm missing, but I couldn't find anything in the documentation. 

Any help would be appreciated.

**Comment by dansiegel** [comment]
it's hard to say what your issue is without a reproduction app. That said all DefaultNavigation does is call the underlying `Shell.GoToAsync` on the Shell instance, so if there is a bug there it would be from Maui itself

**Comment by indyjason79** [comment]
> it's hard to say what your issue is without a reproduction app. 

The sample application in this repo can be used. That's what I used to test the issue I was having. Just try to navigate using the Navigation property in any view model and see it doesn't work.

> That said all DefaultNavigation does is call the underlying `Shell.GoToAsync` on the Shell instance, so if there is a bug there it would be from Maui itself

DefaultNavigation is using Shell that is injected into the class instead of the static Shell class. If you use the static Shell class to navigate it works, but if you use Shell that is injected navigation does not work. I could be wrong, but that does not seem like a Maui issue to me. I just updated my initial comment about this.

**Comment by dansiegel** [comment]
Running a test on this. It seems that Shell.Current and the Shell instance injected into the DefaultNavigation service are different instances. You should be able to fix this temporarily by adding:
`builder.Services.AddSingleton<Shell, YourAppShell>();`

I'll have a fix for it soon.
