### ISSUE TITLE
[Bug] UseMauiMicroMvvm<TApp, TShell> and the loading of resources

### ISSUE THREAD

**Issue by MilKAOS** [AvantiPoint/mauimicromvvm#10]
We noticed that if you have an App with StaticResources and use _UseMauiMicroMvvm<TApp, TShell>_ the StaticResources have not only to be declared in the call of _UseMauiMicroMvvm_ but also in the App.xaml in the ResourceDictionary otherwise they will not be used. (We tested it with using the StaticResources in the Flyout Menu.)

The reason is, we think, the order of operations in _UseMauiMicroMvvm<TApp, TShell>_. From our point of view the (mergedDictionary) resources have to be added before the Shell is created and the MainPage is set.

Another question we have is about the use of _UseMauiMicroMvvm<Application, TShell>(resources, mergedDictionaries)_: The LoadFromXaml would always overwrite any given resources from _resources_ (if _mergedDictionaries_ has entries)?

**Comment by dansiegel** [comment]
closed by #12
