### ISSUE TITLE
[Discussion] IViewFactory/ViewFactory public?

### ISSUE THREAD

**Issue by MilKAOS** [AvantiPoint/mauimicromvvm#11]
Would it make sense to declare IViewFactory and ViewFactory public and make the public methods virtual?

We are thinking about adding more functionality into our apps that control the lifecycle of the Shell pages (or at least of the content). To reach that with the help of MauiMicroMVVM it would be nice to be able to inherit from ViewFactory and override some of the public methods.
At the moment the only possibility we see, is to implement a new ViewFactory while copying most of the code of the original ViewFactory.
Would it be an option to make IViewFactory/ViewFactor more open?

**Comment by dansiegel** [comment]
sorry @MilKAOS I think you posted this while I was on vacation and I missed this... the short answer is yes it would totally be possible

**Comment by MilKAOS** [comment]
Thank you for the change, Dan!
Would you like to make a new version for all the changes over the last year?
