### ISSUE TITLE
Add RaisePropertyChanged method on MauiMicroViewModel

### ISSUE THREAD

**Issue by cfasol** [AvantiPoint/mauimicromvvm#16]
I think is very usefull allow to invoke PropertyChanged event from custom viewmodel that ineherits MauiMicroViewModel.
it should be easy to add and it should permits to force the property changed when into the view model there is a complex property and there is a change to the child property.

What do you think about it?

**Comment by dansiegel** [comment]
Not sure I follow. Are you talking about refactoring so that you have something like:

```cs
protected void RaisePropertyChanging(string propertyName);
protected void RaisePropertyChanged(string propertyName);
```

**Comment by cfasol** [comment]
like this: 
```
protected virtual void RaisePropertyChanging([CallerMemberName] string? propertyName = null)
    {
        PropertyChanging?.Invoke(this, new PropertyChangingEventArgs(propertyName));
    }

    protected virtual void RaisePropertyChanged([CallerMemberName] string? propertyName = null)
    {
        PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
    }
```

**Comment by dansiegel** [comment]
I don't see an issue with it... if you'd like to submit a PR I'd be happy to merge it
