### ISSUE TITLE
[Bug] Some PageDialogs DisplayAlerts return Task instead of Task<bool>

### ISSUE THREAD

**Issue by MilKAOS** [AvantiPoint/mauimicromvvm#8]
Hello Dan, we were looking into your code and saw in PageDialogs that two of the DisplayAlerts should have `Task<bool>` as return value and not Task.

Here some snippet from the Microsoft.Maui.Controls assembly:
![image](https://user-images.githubusercontent.com/18283597/229136172-ff88b2b2-9456-40a4-9fb7-ddb6a8b7fb72.png)

**Comment by dansiegel** [comment]
Good catch would you like to submit a PR?

**Comment by MilKAOS** [comment]
Yeah, of course.

**Comment by dansiegel** [comment]
closed by #9
